### PR TITLE
Fix #439

### LINKED ISSUE #439: [FEATURE REQUEST] Query subcollection using structuredQuery
**Is your feature request related to a problem? Please describe.**
I have a database structured as 

collection1
|_document1
   |_collection2
      |_document2
         |_fields

I want to query all documents in the collection2 that respond to a certain criteria.
[Query method](https://github.com/GodotNuts/GodotFirebase/blob/cfbab9d5e3dc3acfc7670f4bbb2c6f2bb472e7d2/addons/godot-firebase/firestore/firestore.gd#L108) uses a url that can't be adjusted to this scenario as the actual URL should be ```projects/[PROJECT_ID]/databases/(default)/documents/collection1/document1:runQuery``` in stead of ```projects/[PROJECT_ID]/databases/(default)/documents/:runQuery```

**Describe the solution you'd like**

- [Add a parameter](https://github.com/GodotNuts/GodotFirebase/blob/cfbab9d5e3dc3acfc7670f4bbb2c6f2bb472e7d2/addons/godot-firebase/firestore/firestore_query.gd#L35) in the **FirestoreQuery** class to customize subpath ```var sub_collection_path: String = ""```
- Change [url](https://github.com/GodotNuts/GodotFirebase/blob/cfbab9d5e3dc3acfc7670f4bbb2c6f2bb472e7d2/addons/godot-firebase/firestore/firestore.gd#L108) path to include the subpath if set. ```var url: String = _base_url + _extended_url + query.sub_collection_path + _query_suffix```

**Describe alternatives you've considered**
Tried different REST combination, but subcollection are not allowed in the where condition. In general '/' is not allowed

**Additional context**
This has been implemented and test with success in my project

### PR DESCRIPTION
**Pull request by zt-pawer**
This is the proposed change for #439

### CODE REVIEW

**Comment by zt-pawer** [comment]
#439

**Comment by WolfgangSenff** [comment]
Sorry, only just remembered this. General question: can you just include the subpath within the definition of the query itself? I think we talked about this in Discord, but I'm not remembering now.

**Comment by zt-pawer** [comment]
Unfortunately in the query definition it goes in the body of the call and it does not accept "/", it seems that the only accepted way is in the URL

**Comment by WolfgangSenff** [comment]
That's obnoxious! Thanks for the fix then - I'll port it over to 4.x. That said, I can't merge at the moment as I'm running out the door, but will do so sometime over the weekend. Nice work and good find!

**Comment by zt-pawer** [comment]
Not a problem

**Review by WolfgangSenff — APPROVED** [review]

**Pull request merged**
